"""feat(webhook): add razorpay_webhooks_events table to record webhook delivery for every event that we have suscribed

Revision ID: 1191ed9af378
Revises: 442eac7b06a4
Create Date: 2026-08-15 22:37:25.503516

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1191ed9af378"
down_revision: Union[str, Sequence[str], None] = "442eac7b06a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "razorpay_webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("razorpay_account_id", sa.String(length=30), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_razorpay_webhook_events_event_hash"),
        "razorpay_webhook_events",
        ["event_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_razorpay_webhook_events_event_type"),
        "razorpay_webhook_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_razorpay_webhook_events_razorpay_account_id"),
        "razorpay_webhook_events",
        ["razorpay_account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_razorpay_webhook_events_razorpay_account_id"),
        table_name="razorpay_webhook_events",
    )
    op.drop_index(
        op.f("ix_razorpay_webhook_events_event_type"),
        table_name="razorpay_webhook_events",
    )
    op.drop_index(
        op.f("ix_razorpay_webhook_events_event_hash"),
        table_name="razorpay_webhook_events",
    )
    op.drop_table("razorpay_webhook_events")
    # ### end Alembic commands ###
