"""feat(user): added otp_veriications table with partial index on user_id where is_used is false

Revision ID: 143faa3eb61e
Revises: 2b73f9871004
Create Date: 2026-07-31 12:37:47.505425

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "143faa3eb61e"
down_revision: Union[str, Sequence[str], None] = "2b73f9871004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("otp_hashed", sa.String(length=255), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_one_valid_otp_per_user",
        "otp_verifications",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_used=false"),
    )
    op.create_index(
        op.f("ix_otp_verifications_email"), "otp_verifications", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_otp_verifications_user_id"),
        "otp_verifications",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_otp_verifications_user_id"), table_name="otp_verifications")
    op.drop_index(op.f("ix_otp_verifications_email"), table_name="otp_verifications")
    op.drop_index(
        "idx_one_valid_otp_per_user",
        table_name="otp_verifications",
        postgresql_where=sa.text("is_used=false"),
    )
    op.drop_table("otp_verifications")
    # ### end Alembic commands ###
