"""feat: added organizer_profiles, events and ticket_tiers tables

Revision ID: 618486e2583b
Revises: 74a1bd83c6ef
Create Date: 2026-08-08 23:26:55.664954

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "618486e2583b"
down_revision: Union[str, Sequence[str], None] = "74a1bd83c6ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizer_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kyc_status",
            sa.Enum("PENDING", "VERIFIED", "REJECTED", name="kyc_status"),
            nullable=False,
        ),
        sa.Column("payout_account_id", sa.String(length=255), nullable=True),
        sa.Column("business_name", sa.String(length=255), nullable=True),
        sa.Column("total_events_hosted", sa.Integer(), nullable=False),
        sa.Column("hold_period_days", sa.Integer(), nullable=False),
        sa.Column("risk_flags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kyc_status != 'VERIFIED' OR (payout_account_id IS NOT NULL AND business_name IS NOT NULL)",
            name="ck_verified_organizer_has_payout_details",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("venue_name", sa.String(length=255), nullable=False),
        sa.Column("venue_address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PUBLISHED", "CANCELLED", "COMPLETED", name="event_status"
            ),
            nullable=False,
        ),
        sa.Column("event_start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sale_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sale_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_tickets_per_user", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_end_time > event_start_time", name="ck_event_end_after_start"
        ),
        sa.CheckConstraint("max_tickets_per_user > 0", name="ck_max_tickets_positive"),
        sa.CheckConstraint(
            "sale_end_at IS NULL OR sale_end_at <= event_start_time",
            name="ck_sales_close_by_event_start",
        ),
        sa.CheckConstraint(
            "sale_start_at <= event_start_time",
            name="ck_sales_open_before_event_starts",
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"], ["organizer_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_city"), "events", ["city"], unique=False)
    op.create_index(
        op.f("ix_events_organizer_id"), "events", ["organizer_id"], unique=False
    )
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_table(
        "ticket_tiers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_capacity", sa.Integer(), nullable=False),
        sa.Column("sold_count", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price >= 0", name="ck_ticket_tier_price_non_negative"),
        sa.CheckConstraint(
            "sold_count >= 0 AND sold_count <= total_capacity",
            name="ck_sold_count_within_capacity",
        ),
        sa.CheckConstraint(
            "total_capacity > 0", name="ck_ticket_tier_capacity_positive"
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "name", name="uq_event_ticket_tier_name"),
    )
    op.create_index(
        op.f("ix_ticket_tiers_event_id"), "ticket_tiers", ["event_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_tiers_event_id"), table_name="ticket_tiers")
    op.drop_table("ticket_tiers")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_organizer_id"), table_name="events")
    op.drop_index(op.f("ix_events_city"), table_name="events")
    op.drop_table("events")
    op.drop_table("organizer_profiles")
    # ### end Alembic commands ###
