"""feat(events) : added events table

Revision ID: 67f18eca7282
Revises: ec878d6eafcc
Create Date: 2026-08-06 23:57:02.800297

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "67f18eca7282"
down_revision: Union[str, Sequence[str], None] = "ec878d6eafcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
