"""feat(organizer): add sync columns for the kyc status

Revision ID: 69b62f9d85cb
Revises: 1191ed9af378
Create Date: 2026-08-16 22:26:06.592493

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69b62f9d85cb"
down_revision: Union[str, Sequence[str], None] = "1191ed9af378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizer_profiles",
        sa.Column(
            "kyc_provider_status_synced_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column(
            "razorpay_account_status_synced_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizer_profiles", "razorpay_account_status_synced_at")
    op.drop_column("organizer_profiles", "kyc_provider_status_synced_at")
    # ### end Alembic commands ###
