"""feat(tickets): added TicketTier model

Revision ID: 74a1bd83c6ef
Revises: 67f18eca7282
Create Date: 2026-08-07 21:22:57.876480

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "74a1bd83c6ef"
down_revision: Union[str, Sequence[str], None] = "67f18eca7282"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
