"""feat(otp_verifications): added the attempt_count column to prevent brute force otp gusses

Revision ID: 89f339d9a0f1
Revises: 9dff4578abab
Create Date: 2026-08-03 00:54:51.113168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89f339d9a0f1"
down_revision: Union[str, Sequence[str], None] = "9dff4578abab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "otp_verifications",
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("otp_verifications", "attempt_count")
    # ### end Alembic commands ###
