"""feat(organizer): add supportingfields for kyc flow

Revision ID: a2a0a37d3631
Revises: ef6cfdcf1ade
Create Date: 2026-08-13 18:57:49.371974

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2a0a37d3631"
down_revision: Union[str, Sequence[str], None] = "ef6cfdcf1ade"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


OLD_VERIFIED_PAYOUT_CHECK_NAME = "ck_verified_organizer_has_payout_details"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizer_profiles",
        sa.Column(
            "razorpay_account_status",
            sa.Enum(
                "created",
                "suspended",
                name="razorpay_account_status",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("razorpay_reference_code", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("razorpay_stakeholder_id", sa.String(length=30), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("razorpay_product_id", sa.String(length=30), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("legal_business_name", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column(
            "business_type",
            sa.Enum(
                "individual",
                "proprietorship",
                "partnership",
                "private_limited",
                "public_limited",
                "llp",
                "trust",
                "society",
                "ngo",
                "not_yet_registered",
                name="organizer_business_type",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("pan_number", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("gst_number", sa.String(length=15), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("contact_email", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("contact_phone", sa.String(length=15), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("bank_account_number", sa.String(length=35), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("bank_ifsc", sa.String(length=11), nullable=True),
    )
    op.add_column(
        "organizer_profiles",
        sa.Column("bank_beneficiary_name", sa.String(length=255), nullable=True),
    )
    # ### end unchanged autogenerate commands ###

    op.create_check_constraint(
        "razorpay_account_status",
        "organizer_profiles",
        "razorpay_account_status IN ('created', 'suspended')",
    )
    op.create_check_constraint(
        "organizer_business_type",
        "organizer_profiles",
        "business_type IN ("
        "'individual', 'proprietorship', 'partnership', 'private_limited', "
        "'public_limited', 'llp', 'trust', 'society', 'ngo', 'not_yet_registered'"
        ")",
    )

    op.alter_column(
        "organizer_profiles",
        "razorpay_account_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_organizer_profiles_razorpay_account_id"),
        "organizer_profiles",
        ["razorpay_account_id"],
        unique=True,
    )

    op.create_unique_constraint(
        "uq_organizer_profiles_razorpay_product_id",
        "organizer_profiles",
        ["razorpay_product_id"],
    )
    op.create_unique_constraint(
        "uq_organizer_profiles_razorpay_reference_code",
        "organizer_profiles",
        ["razorpay_reference_code"],
    )

    op.execute(
        "UPDATE organizer_profiles "
        "SET kyc_provider_status = 'requested' "
        "WHERE kyc_provider_status = 'created'"
    )
    op.execute(
        "UPDATE organizer_profiles "
        "SET kyc_provider_status = NULL "
        "WHERE kyc_provider_status = 'rejected'"
    )

    op.alter_column(
        "organizer_profiles",
        "kyc_provider_status",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "requested",
            "under_review",
            "needs_clarification",
            "activated",
            "suspended",
            name="kyc_provider_status",
            native_enum=False,
            length=30,
        ),
        existing_nullable=True,
    )

    op.create_check_constraint(
        "kyc_provider_status",
        "organizer_profiles",
        "kyc_provider_status IN "
        "('requested', 'under_review', 'needs_clarification', 'activated', 'suspended')",
    )

    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE kyc_status ADD VALUE IF NOT EXISTS 'IN_REVIEW' AFTER 'PENDING'"
        )
        op.execute(
            "ALTER TYPE kyc_status ADD VALUE IF NOT EXISTS 'ACTION_REQUIRED' AFTER 'IN_REVIEW'"
        )

    op.create_index(
        op.f("ix_organizer_profiles_kyc_status"),
        "organizer_profiles",
        ["kyc_status"],
        unique=False,
    )

    op.drop_constraint(
        OLD_VERIFIED_PAYOUT_CHECK_NAME, "organizer_profiles", type_="check"
    )
    op.create_check_constraint(
        "ck_verified_organizer_has_payout_details",
        "organizer_profiles",
        "kyc_status != 'VERIFIED' OR ("
        "razorpay_account_id IS NOT NULL AND "
        "razorpay_stakeholder_id IS NOT NULL AND "
        "razorpay_product_id IS NOT NULL AND "
        "legal_business_name IS NOT NULL AND "
        "bank_account_number IS NOT NULL AND "
        "kyc_provider_status = 'activated'"
        ")",
    )
    op.create_check_constraint(
        "ck_no_provider_status_before_pending",
        "organizer_profiles",
        "(kyc_provider_status IS NOT NULL) OR (kyc_status = 'PENDING')",
    )
    op.create_check_constraint(
        "ck_activated_provider_status_implies_verified",
        "organizer_profiles",
        "(kyc_provider_status != 'activated') OR (kyc_status = 'VERIFIED')",
    )
    op.create_check_constraint(
        "ck_pan_number_format",
        "organizer_profiles",
        "pan_number IS NULL OR pan_number ~ '^[A-Z]{5}[0-9]{4}[A-Z]$'",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_pan_number_format", "organizer_profiles", type_="check")
    op.drop_constraint(
        "ck_activated_provider_status_implies_verified",
        "organizer_profiles",
        type_="check",
    )
    op.drop_constraint(
        "ck_no_provider_status_before_pending", "organizer_profiles", type_="check"
    )
    op.drop_constraint(
        "ck_verified_organizer_has_payout_details", "organizer_profiles", type_="check"
    )
    op.create_check_constraint(
        OLD_VERIFIED_PAYOUT_CHECK_NAME,
        "organizer_profiles",
        "kyc_status != 'VERIFIED' OR "
        "(razorpay_account_id IS NOT NULL AND business_name IS NOT NULL)",
    )

    op.drop_index(
        op.f("ix_organizer_profiles_kyc_status"), table_name="organizer_profiles"
    )

    op.drop_constraint("kyc_provider_status", "organizer_profiles", type_="check")
    op.alter_column(
        "organizer_profiles",
        "kyc_provider_status",
        existing_type=sa.Enum(
            "requested",
            "under_review",
            "needs_clarification",
            "activated",
            "suspended",
            name="kyc_provider_status",
            native_enum=False,
            length=30,
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.execute(
        "UPDATE organizer_profiles "
        "SET kyc_provider_status = 'created' "
        "WHERE kyc_provider_status = 'requested'"
    )

    op.drop_constraint(
        "uq_organizer_profiles_razorpay_reference_code",
        "organizer_profiles",
        type_="unique",
    )
    op.drop_constraint(
        "uq_organizer_profiles_razorpay_product_id",
        "organizer_profiles",
        type_="unique",
    )

    op.drop_index(
        op.f("ix_organizer_profiles_razorpay_account_id"),
        table_name="organizer_profiles",
    )
    op.alter_column(
        "organizer_profiles",
        "razorpay_account_id",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )

    op.drop_constraint("organizer_business_type", "organizer_profiles", type_="check")
    op.drop_constraint("razorpay_account_status", "organizer_profiles", type_="check")

    op.drop_column("organizer_profiles", "bank_beneficiary_name")
    op.drop_column("organizer_profiles", "bank_ifsc")
    op.drop_column("organizer_profiles", "bank_account_number")
    op.drop_column("organizer_profiles", "contact_phone")
    op.drop_column("organizer_profiles", "contact_email")
    op.drop_column("organizer_profiles", "gst_number")
    op.drop_column("organizer_profiles", "pan_number")
    op.drop_column("organizer_profiles", "business_type")
    op.drop_column("organizer_profiles", "legal_business_name")
    op.drop_column("organizer_profiles", "razorpay_product_id")
    op.drop_column("organizer_profiles", "razorpay_stakeholder_id")
    op.drop_column("organizer_profiles", "razorpay_reference_code")
    op.drop_column("organizer_profiles", "razorpay_account_status")
    # ### end Alembic commands ###
