"""feat(organizers) added organizer_profiles table

Revision ID: ec878d6eafcc
Revises: 89f339d9a0f1
Create Date: 2026-08-05 22:14:35.291808

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ec878d6eafcc"
down_revision: Union[str, Sequence[str], None] = "89f339d9a0f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
